name = "floating-admin"
main = "src/index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_PASSWORD = "admin"

[[d1_databases]]
binding = "DB"
database_name = "floating-db"
database_id = "4a7609c3-446c-40f1-8e28-34c498a44757"
