name = "floating-admin"
main = "src/index.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_PASSWORD = "Bobo@886688"

[[d1_databases]]
binding = "DB"
database_name = "floating-db"
database_id = "74344fe6-7b65-495c-9df4-36edcbfc0864"
